global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'product-service'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
